eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Training
    username: Admin
    password: Admin@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
   show-sql: true
   hibernate.ddl-auto: update
